### ISSUE TITLE
OSFV status presentation

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/presentations#30]
Please let me know if you are okay with doing the presentation at DUG#5; if not, I will do it.

We need a feature matrix of OSFV and rough roadmaps in graphical form.
Features are:
- supported hardware - we already have it; we have to announce the state and if new platforms were added, if there are guides on how to add new platform
- CI/CD integration - if someone wants
- outreach plan - plan to get attention from other projects e.g. EDKII
- list of supported features - a group of tests that lead to feature matrix, we should slowly build something that has marketing value for OSFV and Dasharo
- external frameworks integration - phoronix, fwts, chipsec etc.
- HCL generations and reporting - both Dasharo and Qubes OS
- clearly communicated commercial offering

**Comment by pietrushnic** [comment]
@macpijan didn't get a response from you, and it is too late since I already published the agenda without OSFV status at DUG#5. Can we agree on having this presentation on DUG#6 (13th June 2024)? If yes, I would appreciate your CfP submission [here](https://cfp.3mdeb.com/developers-vpub-0xb-2024/)

**Comment by macpijan** [comment]
Submitted

**Comment by pietrushnic** [comment]
We scheduled this presentation for DUG#6, I'm just waiting for confirmation before I can close this issue.

**Comment by pietrushnic** [comment]
https://cfp.3mdeb.com/developers-vpub-0xb-2024/speaker/CL7STR/
